from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, -40, 641, 652))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.Sagittal_slice = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Sagittal_slice.setText("")
        self.Sagittal_slice.setPixmap(QtGui.QPixmap("Images/img_1.png"))
        self.Sagittal_slice.setScaledContents(True)
        self.Sagittal_slice.setObjectName("Sagittal_slice")
        self.gridLayout.addWidget(self.Sagittal_slice, 2, 2, 1, 1)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.gridLayoutWidget)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.gridLayout.addWidget(self.verticalScrollBar, 2, 1, 1, 1)
        self.verticalScrollBar_3 = QtWidgets.QScrollBar(self.gridLayoutWidget)
        self.verticalScrollBar_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_3.setObjectName("verticalScrollBar_3")
        self.gridLayout.addWidget(self.verticalScrollBar_3, 5, 1, 1, 1)
        self.Sagittal_title = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Sagittal_title.setObjectName("Sagittal_title")
        self.gridLayout.addWidget(self.Sagittal_title, 0, 2, 1, 1)
        self.Volume_Title = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Volume_Title.setObjectName("Volume_Title")
        self.gridLayout.addWidget(self.Volume_Title, 4, 2, 1, 1)
        self.Axial_title = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Axial_title.setObjectName("Axial_title")
        self.gridLayout.addWidget(self.Axial_title, 0, 0, 1, 1)
        self.Coroanl_title = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Coroanl_title.setObjectName("Coroanl_title")
        self.gridLayout.addWidget(self.Coroanl_title, 4, 0, 1, 1)
        self.CoronalSlice = QtWidgets.QLabel(self.gridLayoutWidget)
        self.CoronalSlice.setText("")
        self.CoronalSlice.setPixmap(QtGui.QPixmap("Images/img_1.png"))
        self.CoronalSlice.setScaledContents(True)
        self.CoronalSlice.setObjectName("CoronalSlice")
        self.gridLayout.addWidget(self.CoronalSlice, 5, 0, 1, 1)
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.gridLayoutWidget)
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.gridLayout.addWidget(self.verticalScrollBar_2, 2, 3, 1, 1)
        self.Volume = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Volume.setScaledContents(True)
        self.Volume.setObjectName("Volume")
        self.gridLayout.addWidget(self.Volume, 5, 2, 1, 1)
        self.AxialSlice = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AxialSlice.setText("")
        self.AxialSlice.setPixmap(QtGui.QPixmap("Images/img_1.png"))
        self.AxialSlice.setScaledContents(True)
        self.AxialSlice.setObjectName("AxialSlice")
        self.gridLayout.addWidget(self.AxialSlice, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_DICOM = QtWidgets.QAction(MainWindow)
        self.actionImport_DICOM.setObjectName("actionImport_DICOM")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionImport_DICOM)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Sagittal_title.setText(_translate("MainWindow", "Sagittal Slice"))
        self.Volume_Title.setText(_translate("MainWindow", "Volume"))
        self.Axial_title.setText(_translate("MainWindow", "Axial Slice"))
        self.Coroanl_title.setText(_translate("MainWindow", "Coroanl SLice"))
        self.Volume.setText(_translate("MainWindow", "Volume"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionImport_DICOM.setText(_translate("MainWindow", "Import DICOM..."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
